#!/usr/bin/env ruby
require 'yaml'
require 'logger'
require File.expand_path('../imap_adapter', __FILE__)
require 'optparse'

log = Logger.new(STDOUT)
log.level = Logger::INFO



options = {}
options[:config] = File.expand_path("../config.yml",  __FILE__ )
OptionParser.new do |opts|
  opts.banner = "Usage: imap_move [options]"

  opts.on("-d", "--[no-]delete", "Delete emptied mailbox") do |d|
    options[:delete] = d
  end
  opts.on("-c", "--config FILE", "Specify config file") do |c|
    options[:config] = c
    puts options[:config]
  end

end.parse!

# load config
AppConfig = YAML.load_file(options[:config])
# Connect into servers
conn_from = ImapAdapter.new(AppConfig['from'])
conn_to   = ImapAdapter.new(AppConfig['to'])

AppConfig['boxes_to_sync'].each do |box_from, box_to|
  # select box_from
  log.info("Selecting \"origin\" box: #{box_from}")
  conn_from.select_box(box_from)
  total_of_messages = conn_from.find_message_ids.size


  log.info("There's #{total_of_messages} messages to move")
  # select or create box_to
  conn_to.select_or_create_box(box_to)
  log.info("Selecting \"destination\" box: #{box_to}")

  # find messages that exist in the destination
  messages_existing = conn_to.find_message_ids

  # a block to execute for each message
  index = 0
  conn_from.for_each_message do |message|
    index += 1
    uid = message.attr['UID']
    message_id = message.attr['ENVELOPE'].message_id
    log.info("processing message uid: ##{uid} (#{index}/#{total_of_messages})")

    # if message exist just remove
    if messages_existing.include?(message_id)
      log.info("Message ##{uid} exixsts in destination")
      conn_from.delete_messages(uid)
      next
    end

    # find message body from original server
    conn_from.copy_message(uid, conn_to, box_to)
    log.info("Message ##{uid} copied to destination")

    # removed message that is copied
    conn_from.delete_messages(uid)
    log.info("Deleted message ##{uid}")
  end
  conn_to.subscribe_box(box_to)
  # remove all messages that is mark to remove
  conn_from.expunge
  total_of_messages = conn_from.find_message_ids.size
  if total_of_messages == 0 and options[:delete]
    log.info("All mails removed")
    log.info("Deleting mailbox.")
    conn_from.delete_box(box_from)
  end
end

conn_to.disconnect
conn_from.disconnect
